[profile.default]
# remove pinning
# solc_version = "0.8.13"
src = 'src'
out = 'out'
libs = ['lib']
[rpc_endpoints]
rinkeby = "${RINKEBY_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
[etherscan]
etherscan_rinkeby = { key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config