[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
[rpc_endpoints]
rinkeby = "${RINKEBY_RPC_URL}"

[etherscan]
rinkeby = { key = "${ETHERSCAN_KEY}" }

# See more config options https://github.com/gakonst/foundry/tree/master/config